### PR TITLE
text attribute criteria filter

### PR DESCRIPTION
**Pull request by gutte**
Addition of a text attribute filter in the list-nodes-by-type view.

### CODE REVIEW

**Comment by jhkurki** [comment]
There are some problems with char encodings, see screenshot

screenshot 2018-10-17 at 15 17 38

**Comment by gutte** [comment]
should be fixed

**Comment by jhkurki** [comment]
nice :) 

I found another issue when typing a space char. If I search with e.g. "alueellinen ter", ui sends  (p.prefLabel:alueellinen ter*) to backend which then throws a parse exception. It should probably send something like (p.prefLabel:alueellinen* AND p.prefLabel:ter*) or  (p.prefLabel:alueellinen AND p.prefLabel:ter*) . 

In similar cases I have used simple tokenization: `var tokens = (query.match(/\S+/g) || []);` then 
`var where = tokens.map(function(t) {
  return "p.prefLabel:" + t + "*";
}).join(" AND "))`. Maybe something similar would be applicable here.

**Comment by gutte** [comment]
I went with your suggested method.

Since we are looking for an exact match with an option from a dropdown, the preferred solution would probably have been to lookup on something like "alueellinen ter*", but i suppose thats an api constraint.

I also comitted an additional change unrelated to the issue you commented on.

**Pull request merged**
